meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MQSeries
abstract: "Interface to IBM's MQSeries Product"
author:
  - 'MQ Engineering Group <mqseries@cpan.org>'
version: 1.35
version_from: MQSeries.pm
installdirs: site
build_requires:
  Params::Validate: 0.89
configure_requires:
  Params::Validate: 0.89
requires:
  Convert::EBCDIC: 0.06
  Params::Validate: 0.89
recommends:
  Test::Pod: 1.20
  Test::Simple: 0.62
license: perl
distribution_type: module
generated_by: util/write_yaml
