#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/ErrorResponseParameters.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros 
#
# (c) 1999, 2000 Morgan Stanley Dean Witter and Co.
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%ErrorResponseParameters =
  (
   1013                                  => [ "ErrorId" ],
   1018                                  => [ "ErrorOffset" ],
   1012                                  => [ "ParameterId" ],
   1014                                  => [ "Selector" ],
   2                                     => [ "CodedCharSetId" ],
  );

1;
