#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/RequestParameters.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros 
#
# (c) 1999, 2000 Morgan Stanley Dean Witter and Co.
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%RequestParameters =
  (
   QueueManager =>
   {
    QMgrAttrs                   => [
                                    1001,                                5,
                                    $RequestValues{QueueManager},
                                   ],

    AuthorityEvent              => [ 47,                                 3 ],
    ChannelAutoDef              => [ 55,                                 3 ],
    ChannelAutoDefEvent         => [ 56,                                 3 ],
    ChannelAutoDefExit          => [ 2026,                               4 ],
    ClusterWorkLoadData         => [ 2034,                               4 ],
    ClusterWorkLoadExit         => [ 2033,                               4 ],
    ClusterWorkLoadLength       => [ 58,                                 3 ],
    DeadLetterQName             => [ 2006,                               4 ],
    DefXmitQName                => [ 2025,                               4 ],
    Force                       => [ 1005,                               3 ],
    InhibitEvent                => [ 48,                                 3 ],
    LocalEvent                  => [ 49,                                 3 ],
    MaxHandles                  => [ 11,                                 3 ],
    MaxMsgLength                => [ 13,                                 3 ],
    MaxUncommittedMsgs          => [ 33,                                 3 ],
    PerformanceEvent            => [ 53,                                 3 ],
    QMgrDesc                    => [ 2014,                               4 ],
    RemoteEvent                 => [ 50,                                 3 ],
    RepositoryName              => [ 2035,                               4 ],
    RepositoryNamelist          => [ 2036,                               4 ],
    StartStopEvent              => [ 52,                                 3 ],
    TriggerInterval             => [ 25,                                 3 ],
   },

   Process =>
   {
    ApplType                    => [
                                    1,                                   3,
                                    $RequestValues{ApplType},
                                   ],
    ProcessAttrs                => [
                                    1003,                                5,
                                    $RequestValues{Process},
                                   ],

    ApplId                      => [ 2001,                               4 ],
    EnvData                     => [ 2007,                               4 ],
    FromProcessName             => [ 3003,                               4 ],
    ProcessDesc                 => [ 2011,                               4 ],
    ProcessName                 => [ 2012,                               4 ],
    Replace                     => [ 1006,                               3 ],
    ToProcessName               => [ 3004,                               4 ],
    UserData                    => [ 2021,                               4 ],
   },

   Queue => 
   {
    DefBind                     => [ 
                                    61,                                  3,
                                    $RequestValues{DefBind},
                                   ],
    DefinitionType              => [
                                    7,                                   3,
                                    $RequestValues{DefinitionType},
                                   ],
    DefInputOpenOption          => [
                                    4,                                   3,
                                    $RequestValues{DefInputOpenOption},
                                   ],
    MsgDeliverySequence         => [
                                    16,                                  3,
                                    $RequestValues{MsgDeliverySequence},
                                   ],
    QAttrs                      => [
                                    1002,                                5,
                                    $RequestValues{Queue},
                                   ],
    QServiceIntervalEvent       => [
                                    46,                                  3,
                                    $RequestValues{QServiceIntervalEvent},
                                   ],
    QType                       => [
                                    20,                                  3,
                                    $RequestValues{QType},
                                   ],
    Scope                       => [
                                    45,                                  3,
                                    $RequestValues{Scope},
                                   ],
    TriggerType                 => [
                                    28,                                  3,
                                    $RequestValues{TriggerType},
                                   ],
    Usage                       => [
                                    12,                                  3,
                                    $RequestValues{Usage},
                                   ],

    BackoutRequeueName          => [ 2019,                               4 ],
    BackoutThreshold            => [ 22,                                 3 ],
    BaseQName                   => [ 2002,                               4 ],
    ClusterInfo                 => [ 1083,                               3 ],
    ClusterName                 => [ 2029,                               4 ],
    ClusterNamelist             => [ 2030,                               4 ],
    DefPersistence              => [ 5,                                  3 ],
    DefPriority                 => [ 6,                                  3 ],
    DistLists                   => [ 34,                                 3 ],
    Force                       => [ 1005,                               3 ],
    FromQName                   => [ 3001,                               4 ],
    HardenGetBackout            => [ 8,                                  3 ],
    InhibitGet                  => [ 9,                                  3 ],
    InhibitPut                  => [ 10,                                 3 ],
    InitiationQName             => [ 2008,                               4 ],
    MaxMsgLength                => [ 13,                                 3 ],
    MaxQDepth                   => [ 15,                                 3 ],
    ProcessName                 => [ 2012,                               4 ],
    Purge                       => [ 1007,                               3 ],
    QDepthHighEvent             => [ 43,                                 3 ],
    QDepthHighLimit             => [ 40,                                 3 ],
    QDepthLowEvent              => [ 44,                                 3 ],
    QDepthLowLimit              => [ 41,                                 3 ],
    QDepthMaxEvent              => [ 42,                                 3 ],
    QDesc                       => [ 2013,                               4 ],
    QName                       => [ 2016,                               4 ],
    QServiceInterval            => [ 54,                                 3 ],
    RemoteQMgrName              => [ 2017,                               4 ],
    RemoteQName                 => [ 2018,                               4 ],
    Replace                     => [ 1006,                               3 ],
    RetentionInterval           => [ 21,                                 3 ],
    Shareability                => [ 23,                                 3 ],
    ToQName                     => [ 3002,                               4 ],
    TriggerControl              => [ 24,                                 3 ],
    TriggerData                 => [ 2023,                               4 ],
    TriggerDepth                => [ 29,                                 3 ],
    TriggerMsgPriority          => [ 26,                                 3 ],
    XmitQName                   => [ 2024,                               4 ],
   },

   Channel =>
   {
    ChannelAttrs                => [
                                    1015,                                5,
                                    $RequestValues{Channel},
                                   ],
    ChannelInstanceAttrs        => [
                                    1524,                                5,
                                    $RequestValues{Channel},
                                   ],
    ChannelInstanceType         => [
                                    1523,                                3,
                                    $RequestValues{ChannelInstanceType},
                                   ],
    ChannelTable                => [
                                    1526,                                3,
                                    $RequestValues{ChannelTable},
                                   ],
    ChannelType                 => [
                                    1511,                                3,
                                    $RequestValues{ChannelType},
                                   ],
    InDoubt                     => [
                                    1516,                                3,
                                    $RequestValues{InDoubt},
                                   ],
    MCAType                     => [
                                    1517,                                3,
                                    $RequestValues{MCAType},
                                   ],
    NonPersistentMsgSpeed       => [
                                    1562,                                3,
                                    $RequestValues{NonPersistentMsgSpeed},
                                   ],
    PutAuthority                => [
                                    1508,                                3,
                                    $RequestValues{PutAuthority},
                                   ],
    TransportType               => [
                                    1501,                                3,
                                    $RequestValues{TransportType},
                                   ],

    BatchInterval               => [ 1564,                               3 ],
    BatchSize                   => [ 1502,                               3 ],
    ChannelDesc                 => [ 3502,                               4 ],
    ChannelName                 => [ 3501,                               4 ],
    ClusterName                 => [ 2029,                               4 ],
    ClusterNamelist             => [ 2030,                               4 ],
    ConnectionName              => [ 3506,                               4 ],
    DataConversion              => [ 1515,                               3 ],
    DataCount                   => [ 1512,                               3 ],
    DiscInterval                => [ 1503,                               3 ],
    FromChannelName             => [ 3007,                               4 ],
    HeartbeatInterval           => [ 1563,                               3 ],
    InitiationQName             => [ 2008,                               4 ],
    LongRetryCount              => [ 1507,                               3 ],
    LongRetryInterval           => [ 1506,                               3 ],
    MCAName                     => [ 3507,                               4 ],
    MCAUserIdentifier           => [ 3527,                               4 ],
    MaxMsgLength                => [ 1510,                               3 ],
    ModeName                    => [ 3503,                               4 ],
    MsgExit                     => [ 3509,                               4 ],
    MsgRetryCount               => [ 1544,                               3 ],
    MsgRetryExit                => [ 3534,                               4 ],
    MsgRetryInterval            => [ 1545,                               3 ],
    MsgRetryUserData            => [ 3535,                               4 ],
    MsgSeqNumber                => [ 1514,                               3 ],
    MsgUserData                 => [ 3514,                               4 ],
    NetworkPriority             => [ 1565,                               3 ],
    Password                    => [ 3518,                               4 ],
    QMgrName                    => [ 2015,                               4 ],
    Quiesce                     => [ 1008,                               3 ],
    ReceiveExit                 => [ 3511,                               4 ],
    ReceiveUserData             => [ 3516,                               4 ],
    Replace                     => [ 1006,                               3 ],
    SecurityExit                => [ 3508,                               4 ],
    SecurityUserData            => [ 3513,                               4 ],
    SendExit                    => [ 3510,                               4 ],
    SendUserData                => [ 3515,                               4 ],
    SeqNumberWrap               => [ 1509,                               3 ],
    ShortRetryCount             => [ 1505,                               3 ],
    ShortRetryInterval          => [ 1504,                               3 ],
    ToChannelName               => [ 3008,                               4 ],
    TpName                      => [ 3504,                               4 ],
    UserIdentifier              => [ 3517,                               4 ],
    XmitQName                   => [ 3505,                               4 ],
   },

   Escape =>
   {
    EscapeType                  => [
                                    1017,                                3,
                                    $RequestValues{EscapeType},
                                   ],

    EscapeText                  => [ 3014,                               4 ],
   },

   Namelist =>
   {
    NamelistAttrs               => [
                                    1004,                                5, 
                                    $RequestValues{Namelist},
                                   ],
    
    FromNamelistName            => [ 3005,                               4 ],
    NamelistDesc                => [ 2009,                               4 ],
    NamelistName                => [ 2010,                               4 ],
    Names                       => [ 2020,                               6 ],
    Replace                     => [ 1006,                               3 ],
    ToNamelistName              => [ 3006,                               4 ],
   },

   Cluster =>
   {
    Action                      => [ 
                                    1086,                                3,
                                    $RequestValues{Action},
                                   ],
    ClusterQMgrAttrs            => [ 
                                    1093,                                5, 
                                    $RequestValues{Cluster},
                                   ],

    Channel                     => [ 3501,                               4 ],
    ClusterName                 => [ 2029,                               4 ],
    ClusterNamelist             => [ 2030,                               4 ],
    QMgrName                    => [ 2031,                               4 ],
    QMgrName                    => [ 2015,                               4 ],
    Quiesce                     => [ 1008,                               3 ],
   },

  );

1;
