#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/RequestValues.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2004 Morgan Stanley Dean Witter and Co.
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%RequestValues =
  (
   #
   # QueueManager
   #
   QueueManager =>
   {
    All                         => 1009,
    AccountingConnOverride      => 136,
    ActivityRecording           => 138,
    AlterationDate              => 2027,
    AlterationTime              => 2028,
    AuthorityEvent              => 47,
    ChannelAutoDef              => 55,
    ChannelAutoDefEvent         => 56,
    ChannelAutoDefExit          => 2026,
    ClusterWorkLoadData         => 2034,
    ClusterWorkLoadExit         => 2033,
    ClusterWorkLoadLength       => 58,
    CodedCharSetId              => 2,
    CommandInputQName           => 2003,
    CommandLevel                => 31,
    CreationDate		=> 2004,
    CreationTime		=> 2005,
    DeadLetterQName             => 2006,
    DefXmitQName                => 2025,
    DistLists                   => 34,
    InhibitEvent                => 48,
    LocalEvent                  => 49,
    MaxHandles                  => 11,
    MaxMsgLength                => 13,
    MaxPriority                 => 14,
    MaxUncommittedMsgs          => 33,
    PerformanceEvent            => 53,
    Platform                    => 32,
    QMgrDesc                    => 2014,
    QMgrIdentifier              => 2032,
    QMgrName                    => 2015,
    RemoteEvent                 => 50,
    RepositoryName              => 2035,
    RepositoryNamelist          => 2036,
    StartStopEvent              => 52,
    SyncPoint                   => 30,
    TriggerInterval             => 25,
   },

   AdoptNewMCACheck =>
   {
    All				=> 1,
    NetworkAddress		=> 4,
    None			=> 0,
    QMgrName			=> 2,
   },

   AdoptNewMCAType =>
   {
    All				=> 1,
    No				=> 0,
   },

   ChannelEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    Exception			=> 2,
   },

   CommandEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    NoDisplay			=> 3,
   },

   Recording =>			# ActivityRecording / TraceRouteRecording
   {
    Disabled			=> 0,
    Msg 			=> 2,
    Queue			=> 1,
   },

   QMgrAccounting =>		# QMgr-level Queue/Channel Accounting
   {
    None			=> -1,
    Off				=> 0,
    On				=> 0,
   },

   QMgrMonitoring =>		# QMgr-level Queue/Channel Monitoring, ChannelStatistics
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None			=> -1,
    Off				=> 0,
   },

   QMgrQueueStatistics =>
   {
    Off                         => 0,
    On                          => 1,
    None                        => -1,
   },

   QMgrServiceControl =>
   {				# ChInitControl, CommandServerControl
    Manual			=> 2,
    QMgr			=> 0,
   },

   QMStatusAttrs =>
   {
    All				=> 1009,

    ChannelInitiatorStatus	=> 1232,
    CommandServerStatus		=> 1233,
    ConnectionCount		=> 1230,
    CurrentLog			=> 3071,
    LogPath			=> 3074,
    MediaRecoveryLog		=> 3073,
    QMgrName 			=> 2015,
    QMgrStatus			=> 1232,
    RestartRecoveryLog		=> 3072
   },

   ReceiveTimeoutType =>
   {
    Add				=> 1,
    Equal			=> 2,
    Multiply			=> 0,
   },

   SharedQQMgrName =>
   {
    Ignore			=> 1,
    Use				=> 0,
   },

   TCPStackType =>
   {
    Multiple                    => 1,
    Single                      => 0,
   },

   #
   # Process
   #
   Process =>
   {
    All                         => 1009,
    AlterationDate              => 2027,
    AlterationTime              => 2028,
    ApplId                      => 2001,
    ApplType                    => 1,
    EnvData                     => 2007,
    ProcessDesc                 => 2011,
    ProcessName                 => 2012,
    ProcessNames                => 3012,
    UserData                    => 2021,
   },

   ApplType =>
   {
    AIX                         => 6,
    CICS                        => 1,
    DOS                         => 5,
    Default                     => 6,
    IMS                         => 3,
    MVS                         => 2,
    NSK                         => 13,
    OS2                         => 4,
    OS400                       => 8,
    UNIX                        => 6,
    VMS                         => 12,
    Win16                       => 9,
    Win32                       => 11,
   },

   #
   # Queue
   #
   Queue =>
   {
    All                         => 1009,
    AlterationDate              => 2027,
    AlterationTime              => 2028,
    BackoutRequeueName          => 2019,
    BackoutThreshold            => 22,
    BaseQName                   => 2002,
    CLWLQueuePriority		=> 96,
    CLWLQueueRank		=> 95,
    CLWLUseQ			=> 98,
    ClusterDate                 => 2037,
    ClusterName                 => 2029,
    ClusterNamelist             => 2030,
    ClusterQType                => 59,
    ClusterTime                 => 2038,
    CreationDate                => 2004,
    CreationTime                => 2005,
    CurrentQDepth               => 3,
    DefBind                     => 61,
    DefInputOpenOption          => 4,
    DefPersistence              => 5,
    DefPriority                 => 6,
    DefinitionType              => 7,
    DistLists                   => 34,
    HardenGetBackout            => 8,
    HighQDepth                  => 36,
    InhibitGet                  => 9,
    InhibitPut                  => 10,
    InitiationQName             => 2008,
    MaxMsgLength                => 13,
    MaxQDepth                   => 15,
    MsgDeliverySequence         => 16,
    MsgDeqCount                 => 38,
    MsgEnqCount                 => 37,
    OpenInputCount              => 17,
    OpenOutputCount             => 18,
    ProcessName                 => 2012,
    QDepthHighEvent             => 43,
    QDepthHighLimit             => 40,
    QDepthLowEvent              => 44,
    QDepthLowLimit              => 41,
    QDepthMaxEvent              => 42,
    QDesc                       => 2013,
    QMgrIdentifier              => 2032,
    QMgrName                    => 2031,
    QName                       => 2016,
    QNames                      => 3011,
    QueueAccounting		=> 134,
    QueueMonitoring		=> 123,
    QueueStatistics		=> 128,
    QServiceInterval            => 54,
    QServiceIntervalEvent       => 46,
    QType                       => 20,
    RemoteQMgrName              => 2017,
    RemoteQName                 => 2018,
    RetentionInterval           => 21,
    Scope                       => 45,
    Shareability                => 23,
    TimeSinceReset              => 35,
    TriggerControl              => 24,
    TriggerData                 => 2023,
    TriggerDepth                => 29,
    TriggerMsgPriority          => 26,
    TriggerType                 => 28,
    Usage                       => 12,
    XmitQName                   => 2024,
   },

   QType =>
   {
    Alias                       => 3,
    All                         => 1001,
    Cluster                     => 7,
    Local                       => 1,
    Model                       => 2,
    Remote                      => 6,
   },

   DefInputOpenOption =>
   {
    Exclusive                   => 4,
    Shared                      => 2,
   },

   MonitoringDft =>		# ClusSdrMonDft, Queue-level QueueMonitoring, Channel-level ChannelMonitoring
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    Off				=> 0,
    QMgr			=> -3,
   },

   MsgDeliverySequence =>
   {
    FIFO                        => 1,
    Priority                    => 0,
   },

   Usage =>
   {
    Normal                      => 0,
    XMITQ                       => 1,
   },

   TriggerType =>
   {
    Depth                       => 3,
    Every                       => 2,
    First                       => 1,
    None                        => 0,
   },

   DefinitionType =>
   {
    Permanent                   => 2,
    Shared			=> 4,
    Temporary                   => 3,
   },

   IGQPutAuthority =>
   {
    AltIGQ			=> 4,
    Context			=> 2,
    Default			=> 1,
    OnlyIGQ			=> 3,
   },

   #
   # IndexType is for queues on z/OS
   #
   IndexType =>
   {
    CorrelId			=> 2,
    GroupId			=> 5,
    MsgId			=> 1,
    MsgToken			=> 4,
    None			=> 0,
   },

   IPAddressVersion =>
   {
    IPv4			=> 0,
    IPv6			=> 1,
   },

   #
   # QueueAccounting is also used for QueueMonitoring
   #
   QueueAccounting =>
   {
    Off				=> 0,
    On				=> 1,
    QMgr			=> -3,
   },

   QueueMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    Off				=> 0,
    QMgr			=> -3,
   },

   NonPersistentMsgClass =>
   {
    High			=> 10,
    Normal			=> 0,
   },

   Scope =>
   {
    Cell                        => 2,
    QMgr                        => 1,
   },

   QServiceIntervalEvent =>
   {
    High                        => 1,
    None                        => 0,
    OK                          => 2,
   },

   #
   # Channels
   #
   Channel =>
   {
    All                         => 1009,
    AlterationDate              => 2027,
    AlterationTime              => 2028,
    BatchHeartBeat              => 1567,
    BatchInterval               => 1564,
    BatchSize                   => 1502,
    Batches                     => 1537,
    BuffersReceived             => 1539,
    BuffersSent                 => 1538,
    BytesReceived               => 1536,
    BytesSent                   => 1535,
    ChannelDesc                 => 3502,
    ChannelInstanceType         => 1523,
    ChannelMonitoring           => 122,
    ChannelName                 => 3501,
    ChannelNames                => 3512,
    ChannelStartDate            => 3529,
    ChannelStartTime            => 3528,
    ChannelStatus               => 1527,
    ChannelStatistics           => 129,
    ChannelType                 => 1511,
    ClusterName                 => 2029,
    ClusterNamelist             => 2030,
    CLWLChannelPriority		=> 1578,
    CLWLChannelRank		=> 1577,
    CLWLChannelWeight		=> 1579,
    ConnectionName              => 3506,
    CurrentLUWID                => 3532,
    CurrentMsgs                 => 1531,
    CurrentSequenceNumber       => 1532,
    DataConversion              => 1515,
    DiscInterval                => 1503,
    HeaderCompression           => 1575,
    HeartbeatInterval           => 1563,
    InDoubtStatus               => 1528,
    LastLUWID                   => 3531,
    LastMsgDate                 => 3525,
    LastMsgTime                 => 3524,
    LastSequenceNumber          => 1529,
    LocalAddress                => 3520,
    LongRetriesLeft             => 1540,
    LongRetryCount              => 1507,
    LongRetryInterval           => 1506,
    MCAJobName                  => 3530,
    MCAName                     => 3507,
    MCAStatus                   => 1542,
    MCAType                     => 1517,
    MCAUserIdentifier           => 3527,
    MaxMsgLength                => 1510,
    MessageCompression          => 1576,
    ModeName                    => 3503,
    MsgExit                     => 3509,
    MsgRetryCount               => 1544,
    MsgRetryExit                => 3534,
    MsgRetryInterval            => 1545,
    MsgRetryUserData            => 3535,
    MsgUserData                 => 3514,
    Msgs                        => 1534,
    NetworkPriority             => 1565,
    NonPersistentMsgSpeed       => 1562,
    Password                    => 3518,
    PutAuthority                => 1508,
    QMgrName                    => 2015,
    ReceiveExit                 => 3511,
    ReceiveUserData             => 3516,
    SecurityExit                => 3508,
    SecurityUserData            => 3513,
    SendExit                    => 3510,
    SendUserData                => 3515,
    SeqNumberWrap               => 1509,
    ShortRetriesLeft            => 1541,
    ShortRetryCount             => 1505,
    ShortRetryInterval          => 1504,
    SSLCipherSpec               => 3544,
    SSLClientAuth               => 1568,
    SSLPeerName                 => 3545,
    StopRequested               => 1543,
    TpName                      => 3504,
    TransportType               => 1501,
    UserIdentifier              => 3517,
    XmitQName                   => 3505,
   },

   ChannelDisposition =>
   {
    All				=> -1,
    Private			=> 4,
    Shared			=> 2,
   },

   ChannelStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr                        => -3,
    Off				=> 0,
   },

   ChannelMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr                        => -3,
    Off				=> 0,
   },

   ChannelType =>
   {
    All                         => 5,
    Clntconn                    => 6,
    ClusterReceiver             => 8,
    ClusterSender               => 9,
    Receiver                    => 3,
    Requester                   => 4,
    Sender                      => 1,
    Server                      => 2,
    Svrconn                     => 7,
   },

   HeaderCompression =>
   {
    None			=> 0,
    System			=> 8,
   },

   MessageCompression =>
   {
    Any				=> 268435455,
    None			=> 0,
    RLE				=> 1,
    ZlibFast			=> 2,
    ZlibHigh			=> 4,
   },

   TransportType =>
   {
    DECnet                      => 5,
    LU62                        => 1,
    NetBIOS                     => 3,
    SPX                         => 4,
    TCP                         => 2,
    UDP                         => 6,
   },

   PutAuthority =>
   {
    Context                     => 2,
    Default                     => 1,
   },

   MCAType =>
   {
    Process                     => 1,
    Thread                      => 2,
   },

   NonPersistentMsgSpeed =>
   {
    Normal                      => 1,
    Fast                        => 2,
   },

   QMgrCLWLUseQ =>		# QMgr-level
   {
    Any				=> 1,
    Local			=> 0,
   },

   QueueCLWLUseQ =>		# Queue-level
   {
    Any				=> 1,
    Local			=> 0,
    QMgr			=> -3,
   },

   ChannelTable =>
   {
    Clntconn                    => 2,
    QMgr                        => 1,
   },

   ChannelInstanceType =>
   {
    Current                     => 1011,
    Saved                       => 1012,
   },

   InDoubt =>
   {
    Backout                     => 2,
    Commit                      => 1,
   },

   SSLClientAuth =>
   {
    Optional                    => 1,
    Required                    => 0,
   },

   #
   # Escape
   #
   EscapeType =>
   {
    MQSC                        => 1,
   },

   #
   # New entries for MQSeries 5.1
   #
   Cluster =>
   {
    All                         => 1009,
    AlterationDate              => 2027,
    AlterationTime              => 2028,
    BatchInterval               => 1564,
    BatchSize                   => 1502,
    ChannelStatus               => 1527,
    ClusterDate                 => 2037,
    ClusterName                 => 2029,
    ClusterTime                 => 2038,
    ConnectionName              => 3506,
    DataConversion              => 1515,
    Description                 => 3502,
    DiscInterval                => 1503,
    HeartbeatInterval           => 1563,
    LongRetryCount              => 1507,
    LongRetryInterval           => 1506,
    MCAName                     => 3507,
    MCAType                     => 1517,
    MCAUserIdentifier           => 3527,
    MaxMsgLength                => 1510,
    ModeName                    => 3503,
    MsgExit                     => 3509,
    MsgRetryCount               => 1544,
    MsgRetryExit                => 3534,
    MsgRetryInterval            => 1545,
    MsgRetryUserData            => 3535,
    MsgUserData                 => 3514,
    NetworkPriority             => 1565,
    NonPersistentMsgSpeed       => 1562,
    Password                    => 3518,
    PutAuthority                => 1508,
    QMgrDefinitionType          => 1084,
    QMgrIdentifier              => 2032,
    QMgrType                    => 1085,
    ReceiveExit                 => 3511,
    ReceiveUserData             => 3516,
    SecurityExit                => 3508,
    SecurityUserData            => 3513,
    SendExit                    => 3510,
    SendUserData                => 3515,
    SeqNumberWrap               => 1509,
    ShortRetryCount             => 1505,
    ShortRetryInterval          => 1504,
    Suspend                     => 1087,
    TpName                      => 3504,
    TransportType               => 1501,
    UserIdentifier              => 3517,
    XmitQName                   => 3505,
   },

   NamelistAttrs =>
   {
    All				=> 1009,

    AlterationDate              => 2027,
    AlterationTime              => 2028,
    NamelistDesc                => 2009,
    NamelistName                => 2010,
    Names                       => 2020,
    NameCount			=> 19,
   },

   Action =>
   {
    ForceRemove                 => 1,
   },

   DefBind =>
   {
    OnOpen                      => 0,
    NotFixed                    => 1,
   },

   ObjectType =>
   {
    AuthInfo			=> 7,
    Namelist			=> 2,
    Process			=> 3,
    Queue			=> 1,
    QueueManager		=> 5,

    Channel			=> 6,

    All				=> 1001,
    AliasQueue			=> 1002,
    ModelQueue			=> 1003,
    LocalQueue			=> 1004,
    RemoteQueue			=> 1005,

    SenderChannel		=> 1007,
    ServerChannel		=> 1008,
    RequesterChannel		=> 1009,
    ReceiverChannel		=> 1010,
    CurrentChannel		=> 1011,
    SavedChannel		=> 1012,
    SvrconnChannel		=> 1013,
    ClntconnChannel		=> 1014,
   },

   #
   # AuthInfo
   #
   AuthInfoAttrs =>
   {
    All                         => 1009,
    AuthInfoConnName            => 2053,
    AuthInfoDesc                => 2046,
    AuthInfoName                => 2045,
    AuthInfoType                => 66,
    LDAPPassword                => 2048,
    LDAPUserName                => 2047,
   },

   AuthInfoType =>
   {
    CRLLDAP                     => 1,
   },

   #
   # Queue Status
   #
   OpenType =>
   {
    All                         => 1,
    Input                       => 2,
    Output                      => 3,
   },

   QStatusAttrs =>
   {
    All                         => 1009,
    ApplTag                     => 3058,
    ApplType                    => 1,
    ChannelName                 => 3501,
    Conname                     => 3506,
    CurrentQDepth               => 3,
    OpenInputCount              => 17,
    OpenOptions                 => 1022,
    OpenOutputCount             => 18,
    ProcessId                   => 1024,
    QName                       => 2016,
    ThreadId                    => 1025,
    UncommittedMsgs             => 1027,
    UserIdentifier              => 3025,
   },

   StatusType =>
   {
    Queue                       => 1105,
    Handle                      => 1104,
   },

   #
   # Namelist
   #
   NamelistType =>
   {
    All				=> 1001,
    AuthInfo			=> 4,
    Cluster			=> 2,
    None			=> 0,
    Queue			=> 1,
   },

   #
   # CF Structure (MQ on z/OS)
   #
   CFStrucAttrs =>
   {
    All                         => 1009,

    AlterationDate              => 2027,
    AlterationTime              => 2028,
    CFLevel                     => 70,
    CFStrucDesc			=> 2052,
    CFStrucName			=> 2039,
    Recovery                    => 71,
   },

   #
   # CF Structure (MQ on z/OS)
   #
   # NOTE: CFStruct is for backwards compatibility with pre-1.24 MQSC
   #       New code should use CFStruc (no final 't')
   #
   CFStructAttrs =>
   {
    All                         => 1009,

    AlterationDate              => 2027,
    AlterationTime              => 2028,
    CFLevel                     => 70,
    CFStructDesc		=> 2052,
    CFStructName		=> 2039,
    Recovery                    => 71,
   },

   #
   # Storage Class (MQ on z/OS)
   #
   StorageClassAttrs =>
   {
    All                         => 1009,

    AlterationDate              => 2027,
    AlterationTime              => 2028,
    PageSetId                   => 62,
    StorageClassDesc		=> 2042,
    StorageClassName		=> 2022,
    XCFGroupName		=> 2043,
    XCFMemberName		=> 2044,
   },

   #
   # QSG Disposition
   #
   QSGDisposition =>
   {
    Copy			=> 1,
    Group			=> 3,
    Private			=> 4,
    QMgr			=> 0,
   },

   #
   # UsageType (for InquireUsage, MQ on z/OS)
   #
   UsageType =>
   {
    All				=> 1009,
    DataSet			=> 1169,
    Pageset			=> 1168,
   },

   #
   # Security (MQ on z/OS)
   #
   SecurityAttrs =>
   {
    All				=> 1009,
    SecurityInterval		=> 1153,
    SecuritySwitch		=> 1154,
    SecurityTimeout		=> 1152,
   },

   SecurityItem =>
   {
    All				=> 0,
    Administration		=> 1,
    Namelist			=> 2,
    Process			=> 3,
    Queue			=> 4,
   },

   #
   # SecurityType is for distributed and z/OS
   #
   SecurityType =>
   {
    AuthorizationService	=> 1,                   	# Default on distributed
    Classes			=> 3,                   # Default on z/OS
    SSL				=> 2,
   },

   #
   # EntityType is for InquireAuthorityRecords (MQ v6 on distributed)
   #
   EntityType =>
   {
    Group			=> 2,
    Principal			=> 1,
   },

   #
   # Authority (MQ v6 on distributed platforms)
   #
   Authority =>
   {
    AltUser			=> 1,
    Browse			=> 2,
    Change			=> 3,
    Clear			=> 4,
    Connect			=> 5,
    Create			=> 6,
    Delete			=> 7,
    Display			=> 8,
    Input			=> 9,
    Inquire			=> 10,
    None			=> 0,
    Output			=> 11,
    PassAllContext		=> 12,
    PassIdentityContext		=> 13,
    Set				=> 14,
    SetAllContext		=> 15,
    SetIdentityContext		=> 16,
   },

   #
   # Authority Profile Atrts (MQ v6 on distributed platforms)
   #
   AuthProfileAttrs =>
   {
    All				=> 1009,
    AuthorizationList		=> 1115,
    EntityName			=> 3068,
    EntityType			=> 1118,
    ObjectType			=> 1016,
   },

   #
   # Authority Service (MQ v6 on distributed platforms)
   #
   AuthServiceAttrs =>
   {
    All				=> 1009,
    InterfaceVersion		=> 1263,
    UserIdSupport		=> 1262,
   },

   #
   # Listener
   #
   ListenerAttrs =>
   {
    All                         => 1009,
    Adapter			=> 1519,
    AlterationDate              => 2027,
    AlterationTime              => 2028,
    Backlog                     => 1602,
    Commands			=> 1520,
    IPAddress                   => 3552,
    ListenerDesc                => 3555,
    ListenerName                => 3554,
    LocalName			=> 3521,
    NetbiosNames		=> 1513,
    Port                        => 1522,
    Sessions			=> 1518,
    Socket			=> 1521,
    StartMode                   => 1601,
    TPName			=> 3504,
    TransportType                => 1501,
   },

   ListenerStartMode =>
   {
    Manual                      => 2,
    QMgr                        => 0,
    QMgrStart                   => 1,
   },

   ListenerTransportType =>
   {
    TCP                         => 2,
    LU62                        => 1,
    NetBIOS                     => 3,
    SPX                         => 4,
   },
   #
   # Service (installable service for distributed MQ v6)
   #
   ServiceAttrs =>
   {
    All				=> 1009,

    AlterationDate              => 2027,
    AlterationTime              => 2028,
    ServiceDesc 		=> 2078,
    ServiceName 		=> 2077,
    StartArguments 		=> 2080,
    StartCommand		=> 2079,
    StartMode 			=> 139,
    StopArguments 		=> 2082,
    StopCommand			=> 2081,
    StderrDestination		=> 2084,
    StdoutDestination		=> 2083,
    ServiceType 		=> 121,
   },

   ServiceStartMode =>
   {
    Manual			=> 2,
    QMgr			=> 0,
    QMgrStart			=> 1,
   },

   ServiceType =>
   {
    Command			=> 0,
    Server			=> 1,
   },

   #
   # Service Status (installable service for distributed MQ v6)
   #
   ServiceStatusAttrs =>
   {
    All				=> 1009,

    ProcessId			=> 1024,
    ServiceDesc 		=> 2078,
    ServiceName 		=> 2077,
    ServiceType 		=> 121,
    StartArguments 		=> 2080,
    StartCommand		=> 2079,
    StartDate			=> 3144,
    StartMode 			=> 139,
    StartTime			=> 3145,
    Status 	 		=> 1260,
    StopArguments 		=> 2082,
    StopCommand			=> 2081,
    StderrDestination		=> 2084,
    StdoutDestination		=> 2083,
   },

   ServiceStatus =>
   {
    Running			=> 2,
    Starting			=> 1,
    Stopping			=> 3,
   },


   #
   # Listener Status
   #
   ListenerStatusAttrs =>
   {
    All                         => 1009,

    Adapter			=> 1519,
    Backlog			=> 1602,
    Commands			=> 1520,
    IPAddress			=> 3552,
    ListenerDesc		=> 3555,
    ListenerName		=> 3554,
    ListenerStatus		=> 1599,
    LocalName			=> 3521,
    NetbiosNames		=> 1513,
    Port			=> 1522,
    ProcessId			=> 1024,
    Sessions			=> 1518,
    Socket			=> 1521,
    StartDate			=> 3556,
    StartMode			=> 1601,
    StartTime			=> 3557,
    TPName			=> 3504,
    TranportType		=> 1501,
   },

   #
   # Inquire Connection for V6
   #
   ConnectionAttrs =>
   {
    All                         => 1009,

    ConnectionId                => 7006,
    ExternalUOWId               => 7005,
    OriginUOWId                 => 7008,
    QMgrUOWId                   => 7009,
    ApplTag                     => 3058,
    ASID                        => 3081,
    OriginName                  => 3088,
    PSBName                     => 3082,
    PSTId                       => 3083,
    TaskNumber                  => 3084,
    TransactionId               => 3085,
    UOWLogExtentName            => 3064,
    UOWLogStartDate             => 3062,
    UOWLogStartTime             => 3063,
    UOWStartDate                => 3060,
    UOWStartTime                => 3061,
    UserId                      => 3025,
    ObjectName                  => 3046,
    ChannelName                 => 3501,
    ConnectionName              => 3506,
    ApplType                    => 1,
    ConnectOptions              => 1108,
    ProcessId                   => 1024,
    ThreadId                    => 1025,
    UOWState                    => 1128,
    UOWType                     => 1132,
    QSGDisp                     => 63,
    HandleState                 => 1028,
    ObjectType                  => 1016,
    OpenOptions                 => 1022,
    },

   ConnInfoType =>
   {
    Conn                        => 1111,
    Handle                      => 1112,
    All                         => 1113,
   },

   FilterParams =>
   {
    Param                        => {
				     ExternalUOWId              => 7005,
				     OriginUOWId                => 7008,
				     QMgrUOWId                  => 7009,
				     ApplType                   => 1,
				     ConnectOptions             => 1108,
				     ProcessId                  => 1024,
				     ThreadId                   => 1025,
				     UOWState                   => 1128,
				     UOWType                    => 1132,
				     QSGDisp                    => 63,
				     HandleState                => 1028,
				     ObjectType                 => 1016,
				     OpenOptions                => 1022,
				     },
    Operator                    => {
				    Greater                     => 4,
				    Less                        => 1,
				    Equal                       => 2,
				    NotEqual                    => 5,
				    NotLess                     => 6,
				    NotGreater                  => 3,
				    Contains                    => 10,
				    Excludes                    => 13,
				   },

   },

   FilterType =>
   {
    ExternalUOWId    => 15,
    OriginUOWId      => 15,
    QMgrUOWId        => 15,
    ApplType         => 13,
    ConnectOptions   => 13,
    ProcessId        => 13,
    ThreadId         => 13,
    UOWState         => 13,
    UOWType          => 13,
    QSGDisp          => 13,
    HandleState      => 13,
    ObjectType       => 13,
    OpenOptions      => 13,
   },


   ByteFilterParams =>
   {
    Param                       => {
				    ExternalUOWId              => 7005,
				    OriginUOWId                => 7008,
				    QMgrUOWId                  => 7009,
				   },

    Operator                    => {
				    Greater                     => 4,
				    Less                        => 1,
				    Equal                       => 2,
				    NotEqual                    => 5,
				    NotLess                     => 6,
				    NotGreater                  => 3,
				   },
   },



   #
   # Morgan Stanley extensions
   #
   MorganEntityType =>
   {
    Principal			=> 1000,
    Group			=> 1001,
    AFS			        => 1002,
   },

  );

1;
