#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/Responses.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2004 Morgan Stanley Dean Witter and Co.
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%Responses =
  (
   Error				=> [ "Error",				$ResponseParameters{Error} ],

   ChangeAuthInfo                   	=> [ 79,                      		$ResponseParameters{AuthInfo} ],
   ChangeCFStruc                   	=> [ 101,                    		$ResponseParameters{CFStruc} ],
   # NOTE: ChangeCFStruct is for backwards compatibility with pre-1.24 MQSC
   ChangeCFStruct                   	=> [ 101,                    		$ResponseParameters{CFStruct} ],
   ChangeChannel                   	=> [ 21,                    		$ResponseParameters{Channel} ],
   ChangeChannelListener                => [ 93,                                 $ResponseParameters{Listener} ],
   ChangeNamelist 			=> [ 32,                     		$ResponseParameters{Namelist} ],
   ChangeProcess 			=> [ 3,                     		$ResponseParameters{Process} ],
   ChangeQueue 				=> [ 8,               			$ResponseParameters{Queue} ],
   ChangeQueueManager 			=> [ 1,                   		$ResponseParameters{QueueManager} ],
   ChangeService 			=> [ 149,                   		$ResponseParameters{Service} ],
   ChangeStorageClass 			=> [ 102,                     		$ResponseParameters{StorageClass} ],

   ClearQueue 				=> [ 9,              			$ResponseParameters{Queue} ],

   CopyAuthInfo				=> [ 80,                    		$ResponseParameters{AuthInfo} ],
   CopyChannel 				=> [ 22,                  		$ResponseParameters{Channel} ],
   CopyChannelListener			=> [ 94,                   		$ResponseParameters{Listener} ],
   CopyProcess 				=> [ 4,                   		$ResponseParameters{Process} ],
   CopyQueue 				=> [ 10,            			$ResponseParameters{Queue} ],
   CopyService 				=> [ 150,                 		$ResponseParameters{Service} ],

   CreateAuthInfo 			=> [ 81,                      		$ResponseParameters{AuthInfo} ],
   CreateCFStruc                   	=> [ 108,                    		$ResponseParameters{CFStruc} ],
   # NOTE: ChangeCFStruct is for backwards compatibility with pre-1.24 MQSC
   CreateCFStruct                   	=> [ 108,                    		$ResponseParameters{CFStruct} ],
   CreateChannel 			=> [ 23,                    		$ResponseParameters{Channel} ],
   CreateChannelListener                       => [ 95,                                 $ResponseParameters{Listener} ],
   CreateNamelist 			=> [ 34,                     		$ResponseParameters{Namelist} ],
   CreateProcess 			=> [ 5,                     		$ResponseParameters{Process} ],
   CreateQueue 				=> [ 11,              			$ResponseParameters{Queue} ],
   CreateService 			=> [ 151,                   		$ResponseParameters{Service} ],
   CreateStorageClass 			=> [ 109,                     		$ResponseParameters{StorageClass} ],

   DeleteAuthInfo 			=> [ 82,                      		$ResponseParameters{AuthInfo} ],
   DeleteAuthorityRecord		=> [ 89,                     		$ResponseParameters{AuthorityRecord} ],
   DeleteCFStruc                   	=> [ 112,                    		$ResponseParameters{CFStruc} ],
   # NOTE: ChangeCFStruct is for backwards compatibility with pre-1.24 MQSC
   DeleteCFStruct                   	=> [ 112,                    		$ResponseParameters{CFStruct} ],
   DeleteChannel 			=> [ 24,                    		$ResponseParameters{Channel} ],
   DeleteChannelListener                       => [ 96,                                 $ResponseParameters{Listener}],
   DeleteNamelist 			=> [ 35,                     		$ResponseParameters{Namelist} ],
   DeleteProcess 			=> [ 6,                     		$ResponseParameters{Process} ],
   DeleteQueue 				=> [ 12,              			$ResponseParameters{Queue} ],
   DeleteService 			=> [ 152,                   		$ResponseParameters{Service} ],
   DeleteStorageClass 			=> [ 113,                     		$ResponseParameters{StorageClass} ],

   Escape 				=> [ 38,            			$ResponseParameters{Escape} ],

   InquireAuthInfo 			=> [ 83,                       		$ResponseParameters{AuthInfo} ],
   InquireAuthInfoNames			=> [ 84,                                 $ResponseParameters{AuthInfo} ],
   InquireAuthorityRecords		=> [ 87,                       		$ResponseParameters{AuthorityRecord} ],
   InquireAuthorityService		=> [ 169,                         	$ResponseParameters{AuthorityService} ],
   InquireCFStruc 			=> [ 115,                     		$ResponseParameters{CFStruc} ],
   InquireCFStrucNames 			=> [ 147,                           	$ResponseParameters{CFStruc} ],
   InquireCFStrucStatus 		=> [ 116,                            	$ResponseParameters{CFStruc} ],
   # NOTE: InquireCFStruct is for backwards compatibility with pre-1.24 MQSC
   InquireCFStruct 			=> [ 115,                     		$ResponseParameters{CFStruct} ],
   InquireCFStructNames 		=> [ 147,                           	$ResponseParameters{CFStruct} ],
   InquireChannel 			=> [ 25,                     		$ResponseParameters{Channel} ],
   InquireChannelNames 			=> [ 20,                           	$ResponseParameters{Channel} ],
   InquireChannelStatus 		=> [ 42,                            	$ResponseParameters{ChannelStatus} ],
   InquireConnection                    => [ 85,                                 $ResponseParameters{Connection} ],
   InquireClusterQueueManager 		=> [ 70,                           	$ResponseParameters{Cluster} ],
   InquireChannelListener               => [ 97,                                 $ResponseParameters{Listener} ],
   InquireChannelListenerStatus		=> [ 98,                             	$ResponseParameters{ListenerStatus} ],
   InquireNamelist 			=> [ 36,                      		$ResponseParameters{Namelist} ],
   InquireNamelistNames 		=> [ 37,                            	$ResponseParameters{Namelist} ],
   InquireProcess 			=> [ 7,                      		$ResponseParameters{Process} ],
   InquireProcessNames 			=> [ 19,                           	$ResponseParameters{Process} ],
   InquireQueue 			=> [ 13,               			$ResponseParameters{Queue} ],
   InquireQueueManager 			=> [ 2,                    		$ResponseParameters{QueueManager} ],
   InquireQueueManagerStatus		=> [ 161,                         	$ResponseParameters{QueueManagerStatus} ],
   InquireQueueNames 			=> [ 18,                     		$ResponseParameters{Queue} ],
   InquireQueueStatus 			=> [ 41,                      		$ResponseParameters{QueueStatus} ],
   InquireSecurity 			=> [ 121,                     		$ResponseParameters{InquireSecurity} ],
   InquireService 			=> [ 153,                    		$ResponseParameters{Service} ],
   InquireServiceStatus			=> [ 154,                           	$ResponseParameters{ServiceStatus} ],
   InquireStorageClass 			=> [ 122,                      		$ResponseParameters{StorageClass} ],
   InquireStorageClassNames		=> [ 148,                            	$ResponseParameters{StorageClass} ],
   InquireUsage 			=> [ 126,                  		$ResponseParameters{InquireUsage} ],

   PingChannel 				=> [ 26,                  		$ResponseParameters{Channel} ],
   PingQueueManager 			=> [ 40,                			$ResponseParameters{QueueManager} ],

   RefreshCluster                       => [ 73,                                 $ResponseParameters{Cluster} ],
   RefreshSecurity			=> [ 78,                      		$ResponseParameters{RefreshSecurity} ],

   ResetChannel 			=> [ 27,                   		$ResponseParameters{Channel} ],
   ResetQueueStatistics 		=> [ 17,                   		$ResponseParameters{Queue} ],

   ResolveChannel 			=> [ 39,                     		$ResponseParameters{Channel} ],

   ReverifySecurity			=> [ 133,                      		$ResponseParameters{ReverifySecurity} ],

   SetAuthorityRecord			=> [ 90,                  		$ResponseParameters{AuthorityRecord} ],


   StartChannel 			=> [ 28,                   		$ResponseParameters{Channel} ],
   StartChannelInitiator 		=> [ 30,                        		$ResponseParameters{Channel} ],
   StartChannelListener                 => [ 31,                            	$ResponseParameters{Listener} ],
   StartService		                => [ 155,                  	        $ResponseParameters{Service} ],

   StopChannel 				=> [ 29,                  		$ResponseParameters{Channel} ],
   StopChannelListener			=> [ 142,                          	$ResponseParameters{Listener} ],
   StopConnection                       => [ 86,                                 $ResponseParameters{Connection} ],
   StopService		                => [ 156,                 	        $ResponseParameters{Service} ],

   #
   # Morgan Stanley extensions
   #
   InquireAuthority 			=> [ 1000,                      		$ResponseParameters{MorganAuthority} ],
   ChangeAuthority 			=> [ 1001,                     		$ResponseParameters{MorganAuthority} ],

  );

1;
