#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/ResponseValues.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros 
#
# (c) 1999 Morgan Stanley Dean Witter and Co.
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%ResponseValues =
  (

   Platform =>
   {
    1                                    => "MVS",
    13                                   => "NSK",
    2                                    => "OS2",
    4                                    => "OS400",
    3                                    => "UNIX",
    5                                    => "Win16",
    11                                   => "Win32",
   },

   QType =>
   {
    3                                    => "Alias",
    7                                    => "Cluster",
    1                                    => "Local",
    2                                    => "Model",
    6                                    => "Remote",
   },

   DefInputOpenOption =>
   {
    4                                    => "Exclusive",
    2                                    => "Shared",
   },

   MsgDeliverySequence =>
   {
    1                                    => "FIFO",
    0                                    => "Priority",
   },

   DefinitionType =>
   {
    2                                    => "Permanent",
    1                                    => "Predefined",
    3                                    => "Temporary",
   },

   Usage =>
   {
    0                                    => "Normal",
    1                                    => "XMITQ",
   },

   TriggerType =>
   {
    3                                    => "Depth",
    2                                    => "Every",
    1                                    => "First",
    0                                    => "None",
   },

   Scope =>
   {
    2                                    => "Cell",
    1                                    => "QMgr",
   },

   QServiceIntervalEvent =>
   {
    1                                    => "High",
    0                                    => "None",
    2                                    => "OK",
   },

   ChannelType =>
   {
    6                                    => "Clntconn",
    8                                    => "ClusterReceiver",
    9                                    => "ClusterSender",
    3                                    => "Receiver",
    4                                    => "Requester",
    1                                    => "Sender",
    2                                    => "Server",
    7                                    => "Svrconn",
   },

   ChannelInstanceType =>
   {
    1011                                 => "Current",
    1012                                 => "Saved",
   },

   MCAStatus =>
   {
    3                                    => "Running", 
    0                                    => "Stopped", 
   },

   TransportType =>
   {
    5                                    => "DECnet",
    1                                    => "LU62",
    3                                    => "NetBIOS",
    4                                    => "SPX",
    2                                    => "TCP",
    6                                    => "UDP",
   },

   PutAuthority =>
   {
    2                                    => "Context",
    1                                    => "Default",
   },

   MCAType =>
   {
    1                                    => "Process",
    2                                    => "Thread",
   },

   NonPersistentMsgSpeed =>
   {
    2                                    => "Fast",
    1                                    => "Normal",
   },

   ChannelStatus =>
   {
    1                                    => "Binding",
    0                                    => "Inactive",
    13                                   => "Initializing",
    8                                    => "Paused",
    7                                    => "Requesting",
    5                                    => "Retrying",
    3                                    => "Running",
    2                                    => "Starting", 
    6                                    => "Stopped",
    4                                    => "Stopping",
   },

   ApplType =>
   {
    1                                    => "CICS",
    5                                    => "DOS",
    3                                    => "IMS",
    2                                    => "MVS",
    4                                    => "OS2",
    8                                    => "OS400",
    6                                    => "UNIX",
    12                                   => "VMS",
    9                                    => "Win16",
    11                                   => "Win32",
   },

   EscapeType =>
   {
    1                                    => "MQSC",
   },

   QMgrDefinitionType =>
   {
    2                                    => "AutoClusterSender",
    4                                    => "AutoExplicitClusterSender",
    3                                    => "ClusterReceiver",
    1                                    => "ExplicitClusterSender",
   },

   QMgrType =>
   {
    0                                    => "Normal",
    1                                    => "Repository",
   },

   ClusterQType =>
   {
    2                                    => "Alias",
    1                                    => "Local",
    4                                    => "QMgrAlias",
    3                                    => "Remote",
   },

   DefBind =>
   {
    1                                    => "NotFixed",
    0                                    => "OnOpen",
   },

  );

1;
