#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/ResponseValues.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros
#
# (c) 1999-2004 Morgan Stanley Dean Witter and Co.
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%ResponseValues =
  (

   Platform =>
   {
    MVS				=> 1,
    NSK				=> 13,
    OS2				=> 2,
    OS400			=> 4,
    UNIX			=> 3,
    Win16			=> 5,
    Win32			=> 11,
   },

   QType =>
   {
    Alias			=> 3,
    Cluster			=> 7,
    Local			=> 1,
    Model			=> 2,
    Remote			=> 6,
   },

   DefInputOpenOption =>
   {
    Exclusive			=> 4,
    Shared			=> 2,
   },

   MsgDeliverySequence =>
   {
    FIFO			=> 1,
    Priority			=> 0,
   },

   DefinitionType =>
   {
    Permanent			=> 2,
    Predefined			=> 1,
    Temporary			=> 3,
   },

   Usage =>
   {
    Normal			=> 0,
    XMITQ			=> 1,
   },

   TriggerType =>
   {
    Depth			=> 3,
    Every			=> 2,
    First			=> 1,
    None			=> 0,
   },

   Scope =>
   {
    Cell			=> 2,
    QMgr			=> 1,
   },

   QServiceIntervalEvent =>
   {
    High			=> 1,
    None			=> 0,
    OK				=> 2,
   },

   ChannelType =>
   {
    Clntconn			=> 6,
    ClusterReceiver		=> 8,
    ClusterSender		=> 9,
    Receiver			=> 3,
    Requester			=> 4,
    Sender			=> 1,
    Server			=> 2,
    Svrconn			=> 7,
   },

   ChannelInstanceType =>
   {
    Current			=> 1011,
    Saved			=> 1012,
   },

   MCAStatus =>
   {
    Running			=> 3,
    Stopped			=> 0,
   },

   TransportType =>
   {
    DECnet			=> 5,
    LU62			=> 1,
    NetBIOS			=> 3,
    SPX				=> 4,
    TCP				=> 2,
    UDP				=> 6,
   },

   PutAuthority =>
   {
    Context			=> 2,
    Default			=> 1,
   },

   MCAType =>
   {
    Process			=> 1,
    Thread			=> 2,
   },

   NonPersistentMsgClass =>
   {
    High			=> 10,
    Normal			=> 0,
   },

   NonPersistentMsgSpeed =>
   {
    Fast			=> 2,
    Normal			=> 1,
   },

   ChannelStatus =>
   {
    Binding			=> 1,
    Inactive			=> 0,
    Initializing		=> 13,
    Paused			=> 8,
    Requesting			=> 7,
    Retrying			=> 5,
    Running			=> 3,
    Starting			=> 2,
    Stopped			=> 6,
    Stopping			=> 4,
   },

   ApplType =>
   {
    CICS			=> 1,
    CHINIT                      => 30,
    DOS				=> 5,
    IMS				=> 3,
    MVS				=> 2,
    NSK                         => 13,
    OS2				=> 4,
    OS400			=> 8,
    QMGR                        => 7,
    UNIX			=> 6,
    USER                        => 25,
    VMS				=> 12,
    Win16			=> 9,
    Win32			=> 11,
   },

   EscapeType =>
   {
    MQSC			=> 1,
   },

   QMgrDefinitionType =>
   {
    AutoClusterSender		=> 2,
    AutoExplicitClusterSender	=> 4,
    ClusterReceiver		=> 3,
    ExplicitClusterSender	=> 1,
   },

   QMgrType =>
   {
    Normal			=> 0,
    Repository			=> 1,
   },

   ClusterQType =>
   {
    Alias			=> 2,
    Local			=> 1,
    QMgrAlias			=> 4,
    Remote			=> 3,
   },

   DefBind =>
   {
    NotFixed			=> 1,
    OnOpen			=> 0,
   },

   ObjectType =>
   {
    AuthInfo                    => 7,
    Listener			=> 11,
    Namelist			=> 2,
    Process			=> 3,
    Queue			=> 1,
    QueueManager		=> 5,
    Service			=> 12,

    Channel			=> 6,

    All				=> 1001,
    AliasQueue			=> 1002,
    ModelQueue			=> 1003,
    LocalQueue			=> 1004,
    RemoteQueue			=> 1005,

    SenderChannel		=> 1007,
    ServerChannel		=> 1008,
    RequesterChannel		=> 1009,
    ReceiverChannel		=> 1010,
    CurrentChannel		=> 1011,
    SavedChannel		=> 1012,
    SvrconnChannel		=> 1013,
    ClntconnChannel		=> 1014,
   },

   #
   # New with WebSphere MQ 5.3
   #
   AuthInfoType =>
   {
    CRLLDAP                     => 1,
   },

   QStatusInputType =>
   {
    Exclusive                   => 2,
    No                          => 0,
    Shared                      => 1,
   },

   QStatusType =>
   {
    Queue			=> 1105,
    Handle			=> 1104,
   },

   SSLClientAuth =>
   {
    Optional                    => 1,
    Required                    => 0,
   },

   #
   # New with MQv6
   #
   AdoptNewMCACheck =>
   {
    All				=> 1,
    NetworkAddress		=> 4,
    None			=> 0,
    QMgrName			=> 2,
   },

   AdoptNewMCAType =>
   {
    All				=> 1,
    No				=> 0,
   },

   #
   # Authority (MQ v6 on distributed platforms)
   #
   Authority =>
   {
    AltUser			=> 1,
    Browse			=> 2,
    Change			=> 3,
    Clear			=> 4,
    Connect			=> 5,
    Create			=> 6,
    Delete			=> 7,
    Display			=> 8,
    Input			=> 9,
    Inquire			=> 10,
    None			=> 0,
    Output			=> 11,
    PassAllContext		=> 12,
    PassIdentityContext		=> 13,
    Set				=> 14,
    SetAllContext		=> 15,
    SetIdentityContext		=> 16,
   },

   ChannelDisposition =>
   {
    All				=> -1,
    Private			=> 4,
    Shared			=> 2,
   },

   ChannelInitiatorControl =>
   {
    Manual			=> 2,
    QMgr			=> 0,
   },

   ChannelEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    Exception			=> 2,
   },

   QMgrChannelMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None                        => -1,
    Off				=> 0,
   },

   QMgrChannelStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None                        => -1,
    Off				=> 0,
   },

   ChannelStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr                        => -3,
    Off				=> 0,
   },

   ChannelMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr                        => -3,
    Off				=> 0,
   },

   ChannelSubState =>
   {
    ChannelAutoDefinitionExit	=> 1200,
    Compressing			=> 1800,
    EndOfBatch			=> 100,
    HeartBeating		=> 600,
    ExecutingMQICall		=> 1700,
    MessageExit			=> 1000,
    NameServerRequest		=> 1400,
    NetworkConnect		=> 1250,
    NetworkReceive		=> 300,
    NetworkSend			=> 200,
    Other			=> 0,
    PerformingMQGET		=> 1600,
    PerformingMQPUT		=> 1500,
    ReceiveExit			=> 800,
    Resynching			=> 500,
    RetryExit			=> 1100,
    SecurityExit		=> 700,
    SendExit			=> 900,
    Serializing			=> 400,
    SSLHandshaking		=> 1300,
   },

   CommandEvent =>
   {
    Disabled			=> 0,
    Enabled			=> 1,
    NoDisplay			=> 3,
   },

   ClusterSenderMonitoringDefault =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr                        => -3,
    Off				=> 0,
   },

   ClusterSenderStatistics =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr                        => -3,
    Off				=> 0,
   },

   #
   # EntityType is for InquireAuthorityRecords (MQ v6 on distributed)
   #
   EntityType =>
   {
    Group			=> 2,
    Principal			=> 1,
    Unknown			=> 3,
   },

   HeaderCompression =>
   {
    None			=> 0,
    System			=> 8,
   },

   IGQPutAuthority =>
   {
    AltIGQ			=> 4,
    Context			=> 2,
    Default			=> 1,
    OnlyIGQ			=> 3,
   },

   IndexType =>
   {
    CorrelId			=> 2,
    GroupId			=> 5,
    MsgId			=> 1,
    MsgToken			=> 4,
    None			=> 0,
   },

   IPAddressVersion =>
   {
    IPv4			=> 0,
    IPv6			=> 1,
   },

   KeepAliveInterval =>
   {
    Auto			=> -1,
   },

   ListenerStartMode =>
   {
    Manual                      => 2,
    QMgr                        => 0,
    QMgrStart                   => 1,
   },

   ListenerStatus =>
   {
    Running                     => 2,
    Starting                    => 1,
    Stopping                    => 3,
   },

   ListenerTransportType =>
   {
    TCP                         => 2,
    LU62                        => 1,
    NetBIOS                     => 3,
    SPX                         => 4,
   },

   MessageCompression =>
   {
    Any				=> 268435455,
    None			=> 0,
    Rle				=> 1,
    ZlibFast			=> 2,
    ZlibHigh			=> 4,
   },

   QMgrChlMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None                        => -1,
    Off				=> 0,
   },

   QMgrClusterMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr			=> -3,
    Off				=> 0,
   },

   QMgrMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    None                        => -1,
    Off				=> 0,
   },

   QueueMonitoring =>
   {
    High			=> 65,
    Low				=> 17,
    Medium			=> 33,
    QMgr                        => -3,
    Off				=> 0,
   },

   QMgrQueueStatistics =>
   {
    Off                         => 0,
    On                          => 1,
    None                        => -1,
   },

   QueueStatistics =>
   {
    Off                         => 0,
    On                          => 1,
    QMgr                        => -3,
   },

   MonitoringDft =>
   {
    Off                         => 0,
    QMgr                        => -3,
    Low                         => 17,
    Medium                      => 33,
    High                        => 65,
   },

   NamelistType =>
   {
    AuthInfo			=> 4,
    Cluster			=> 2,
    None			=> 0,
    Queue			=> 1,
   },

   SharedQQmgrName =>
   {
    Ignore			=> 1,
    Use				=> 0,
   },

   QMgrCLWLUseQ =>		# QMgr-level
   {
    Any				=> 1,
    Local			=> 0,
   },

   CommandServerControl =>
   {
    Manual			=> 2,
    QMgr			=> 0,
   },

   QMgrServiceStatus =>
   {
    Starting			=> 1,
    Running			=> 2,
    Stopped			=> 0,
    Stopping			=> 3,
   },

   QMgrStatus =>
   {
    Starting			=> 1,
    Running			=> 2,
    Quiescing			=> 3,
   },

   QueueCLWLUseQ =>		# Queue-level
   {
    Any				=> 1,
    Local			=> 0,
    QMgr			=> -3,
   },

   QueueAccounting =>
   {
    On                         => 1,
    Off                        => 0,
    QMgr                       => -3,
   },

   QMgrAccounting =>		# QMgr-level QueueAccounting
   {
    None                       => -1,
    On                         => 1,
    Off                        => 0,
   },

   QSharingGroupDisposition =>
   {
    Copy			=> 1,
    Group			=> 3,
    QMgr			=> 0,
    Shared			=> 2,
   },

   QSGDisposition =>
   {
    Copy			=> 1,
    Group			=> 3,
    QMgr			=> 0,
    Shared			=> 2,
   },

   ReceiveTimeoutType =>
   {
    Add				=> 1,
    Equal			=> 2,
    Multiply			=> 0,
   },

   ActivityRecording =>
   {
    Disabled                    => 0,
    Msg                         => 2,
    Queue                       => 1,
   },

   SecuritySwitch =>
   {
    AlternateUser		=> 7,
    Command			=> 8,
    CommandResource		=> 11,
    Connection			=> 9,
    Context			=> 6,
    Namelist			=> 2,
    QMgr			=> 15,
    QSG				=> 16,
    Queue			=> 3,
    Process			=> 1,
    Subsystem			=> 10,
   },

   SecuritySwitchSetting =>
   {
    OffError			=> 25,
    OffFound			=> 21,
    OffNotFound			=> 23,
    OnFound			=> 22,
    OnNotFound			=> 24,
    OnOverridden		=> 26,
   },

   StartMode =>
   {
    Manual			=> 2,
    QMgr			=> 0,
    QMgrStart			=> 1,
   },

   ServiceStatus =>
   {
    Running			=> 2,
    Starting			=> 1,
    Stopping			=> 3,
   },

   ServiceType =>
   {
    Command			=> 0,
    Server			=> 1,
   },

   TCPStackType =>
   {
    Multiple                    => 1,
    Single                      => 0,
   },

   TraceRouteRecording =>
   {
    Disabled                    => 0,
    Msg                         => 2,
    Queue                       => 1,
   },

   #
   # The UsageXXX hashes are for the 'InquireUsage' command for MQ on z/OS
   #
   UsageType =>
   {
    BufferPool			=> 1170,
    DataSet			=> 1169,
    Pageset			=> 1168,
   },

   UsageDataSetType =>
   {
    OldestActiveUOW		=> 10,
    OldestCFRecovery		=> 12,
    OldestPSRecovery		=> 11,
   },

   UsageExpandType =>
   {
    None			=> 3,
    User			=> 1,
    System			=> 2,
   },

   UsagePageSetStatus =>
   {
    Available			=> 0,
    Defined			=> 1,
    NotDefined			=> 3,
    Offline			=> 2,
   },

   #
   # For CFStruc on V6
   CFStatusType =>
   {
    CFStatusSummary             => 1136,
    CFStatusConnect             => 1137,
    CFStatusBackup              => 1138,
   },

   CFStrucStatus =>
   {
    Active			=> 1,
    Failed			=> 4,
    NotFound			=> 0,
    InBackup			=> 3,
    InRecover			=> 2,
    Unknown			=> 6,
   },

   CFStrucType =>
   {
    Admin			=> 1,
    Appl			=> 0,
   },

   #
   # For Inquire Connection in V6
   #
   ConnInfoType =>
   {
    Conn                        => 1111,
    Handle                      => 1112,
    All                         => 1113
    },

   HandleObjectType =>
   {
    Queue                      => 1,
    Process                    => 3,
    Namelist                   => 2,
    QMgr                       => 5,
    Channel                    => 6,
    AuthInfo                   => 7,
    },

   HandleQSGDisposition =>
   {
    Copy                      => 1,
    QMgr                      => 0,
    Shared                    => 2,
   },

   ConnApplType =>
   {
    QMgr                      => 7,
    ChannelInitiator          => 30,
    User                      => 25,
    Batch                     => 32,
    RRSBatch                  => 33,
    CICS                      => 1,
    IMS                       => 3,
   },

   HandleState =>
   {
    Active     	               => 1,
    Inactive   	               => 0,
    },

   UOWState =>
   {
    None			=> 0,
    Active			=> 1,
    Prepared			=> 2,
    Unresolved			=> 3,
   },

   UOWType =>
   {
    QMgr			=> 0,
    CICS			=> 1,
    RRS				=> 2,
    IMS				=> 3,
    XA				=> 4,
   },

   #
   # InquireGroup to query about QSG via a qmgr
   #
   QSGStatus =>
   {
    Active			=> 2,
    Created			=> 1,
    Inactive			=> 3,
    Failed			=> 4,
    Pending			=> 5,
    Unknown			=> 0,
   },

   CommandInformation =>
   {
    DB2ObsoleteMsgs		=> 20,
   },

   #
   # InquireLog for z/OS
   #
   OffLoadStatus =>
   {
    AllocatingArchive		=> 34,
    Available			=> 32,
    CopyingBSDS			=> 35,
    CopyingLog			=> 36,
    Busy			=> 30,
   },

   #
   # InquireSystem for z/OS
   #
   ParameterType =>
   {
    Initial			=> 10,
    Set				=> 11,
   },

   ClusterCacheType =>
   {
    Static			=> 0,
    Dynamic			=> 1,
   },

   WLMIntervalUnits =>
   {
    Seconds			=> 1,
    Minutes			=> 0,
   },

   #
   # Used with the Morgan Stanley extended Authority commands
   #
   MorganEntityType =>
   {
    Principal			=> 1000,
    Group			=> 1001,
    AFS			        => 1002,
   },

  );

1;
