#
# WARNING: This file is automatically generated.
# Any changes made here will be mercilessly lost.
#
# You have been warned, infidel.
#
# P.S. For the real source to this file, see:
#
#    ..../src/pre.in/MQSeries/Command/PCF/Responses.in
#
# and for the evil hackery used to generate this, see:
#
#    ..../src/util/flatten_macros 
#
# (c) 1999 Morgan Stanley Dean Witter and Co.
# See ..../src/LICENSE for terms of distribution.
#
package MQSeries::Command::PCF;

%Responses =
  (
   21                                    => [ "ChangeChannel",                   $ResponseParameters{Channel} ],
   3                                     => [ "ChangeProcess",                   $ResponseParameters{Process} ],
   8                                     => [ "ChangeQueue",                     $ResponseParameters{Queue} ],
   1                                     => [ "ChangeQueueManager",              $ResponseParameters{QueueManager} ],
   9                                     => [ "ClearQueue",                      $ResponseParameters{Queue} ],
   22                                    => [ "CopyChannel",                     $ResponseParameters{Channel} ],
   4                                     => [ "CopyProcess",                     $ResponseParameters{Process} ],
   10                                    => [ "CopyQueue",                       $ResponseParameters{Queue} ],
   23                                    => [ "CreateChannel",                   $ResponseParameters{Channel} ],
   5                                     => [ "CreateProcess",                   $ResponseParameters{Process} ],
   11                                    => [ "CreateQueue",                     $ResponseParameters{Queue} ],
   24                                    => [ "DeleteChannel",                   $ResponseParameters{Channel} ],
   6                                     => [ "DeleteProcess",                   $ResponseParameters{Process} ],
   12                                    => [ "DeleteQueue",                     $ResponseParameters{Queue} ],
   38                                    => [ "Escape",                          $ResponseParameters{Escape} ],
   25                                    => [ "InquireChannel",                  $ResponseParameters{Channel} ],
   20                                    => [ "InquireChannelNames",             $ResponseParameters{Channel} ],
   42                                    => [ "InquireChannelStatus",            $ResponseParameters{Channel} ],
   70                                    => [ "InquireClusterQueueManager",      $ResponseParameters{Cluster} ],
   36                                    => [ "InquireNamelist",                 $ResponseParameters{Namelist} ],
   37                                    => [ "nquireNamelistNames",             $ResponseParameters{Namelist} ],
   7                                     => [ "InquireProcess",                  $ResponseParameters{Process} ],
   19                                    => [ "InquireProcessNames",             $ResponseParameters{Process} ],
   13                                    => [ "InquireQueue",                    $ResponseParameters{Queue} ],
   2                                     => [ "InquireQueueManager",             $ResponseParameters{QueueManager} ],
   18                                    => [ "InquireQueueNames",               $ResponseParameters{Queue} ],
   26                                    => [ "PingChannel",                     $ResponseParameters{Channel} ],
   40                                    => [ "PingQueueManager",                $ResponseParameters{QueueManager} ],
   27                                    => [ "ResetChannel",                    $ResponseParameters{Channel} ],
   17                                    => [ "ResetQueueStatistics",            $ResponseParameters{Queue} ],
   39                                    => [ "ResolveChannel",                  $ResponseParameters{Channel} ],
   28                                    => [ "StartChannel",                    $ResponseParameters{Channel} ],
   30                                    => [ "StartChannelInitiator",           $ResponseParameters{Channel} ],
   31                                    => [ "StartChannelListener",            $ResponseParameters{Channel} ],
   29                                    => [ "StopChannel",                     $ResponseParameters{Channel} ],
  );

1;
